#!/bin/bash
# cp mycotacao/mycotacao/settings.py Mycotacao/mycotacao/mycotacao/settings_old.py
cp settings_site.py mycotacao/mycotacao/settings.py
mv mycotacao/db.sqlite3 ..

python mycotacao/manage.py collectstatic
