# Generated by Django 4.0 on 2024-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='lances',
            field=models.ManyToManyField(to='appCotacao.Lance'),
        ),
        migrations.RemoveField(
            model_name='lance',
            name='estrutura',
        ),
    ]
