# Generated by Django 4.0 on 2024-10-29 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0002_rename_nomeempresa_customuser_nome_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrutura',
            name='fornecedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appCotacao.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lance',
            name='dono',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appCotacao.customuser', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='fornecedor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('produto', 'fornecedor', 'projeto')},
        ),
    ]
