# Generated by Django 4.0 on 2024-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0002_alter_lance_unique_together_estrutura_lances_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lance',
            options={'ordering': ['lance']},
        ),
        migrations.RemoveField(
            model_name='estrutura',
            name='lance_vencedor',
        ),
        migrations.RemoveField(
            model_name='lance',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='lance_atual',
        ),
        migrations.AddField(
            model_name='estrutura',
            name='total_lances',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='estrutura',
            name='status',
            field=models.CharField(choices=[('1', 'Cotando'), ('2', 'Aceitar ou Recusar'), ('3', 'Finalizado'), ('5', 'Finalizado sem acordo')], max_length=1, null=True),
        ),
    ]
