# Generated by Django 4.0 on 2024-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0002_fornecedor_dono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='produtos',
        ),
        migrations.AddField(
            model_name='projeto',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='appCotacao.Produto'),
        ),
    ]
