# Generated by Django 4.0 on 2025-03-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0003_estrutura_fornecedor_lance_dono_projeto_fornecedor_and_more'),
    ]

    operations = [
    ]
