# Generated by Django 4.0 on 2025-03-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0004_auto_20250302_0013'),
    ]

    operations = [
    ]
