# Generated by Django 4.0 on 2024-07-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0004_remove_projeto_produtos_projeto_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='fornecedores',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='produto',
        ),
    ]
