# Generated by Django 4.0 on 2025-03-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0005_auto_20250302_0020'),
    ]

    operations = [
    ]
