# Generated by Django 4.0 on 2024-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0007_remove_projeto_produtos_produto_projetos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='projetos',
        ),
        migrations.AddField(
            model_name='projeto',
            name='produtos',
            field=models.ManyToManyField(to='appCotacao.Produto'),
        ),
    ]
