# Generated by Django 4.0 on 2025-03-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0007_rename_estrutura_cotacao_alter_projeto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='volume',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='ultimo_lance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_lance', to='appCotacao.lance'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.CharField(choices=[('1', 'Cotando'), ('2', 'Aceitar ou Recusar'), ('3', 'Finalizado com acordo'), ('5', 'Finalizado sem acordo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lance',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], max_length=1, null=True),
        ),
    ]
