# Generated by Django 4.0 on 2024-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0008_remove_produto_projetos_projeto_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='produtos',
            new_name='produto',
        ),
    ]
