# Generated by Django 4.0 on 2025-03-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0008_remove_cotacao_volume_cotacao_ultimo_lance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lance',
            options={'ordering': ['sequencia']},
        ),
        migrations.RenameField(
            model_name='lance',
            old_name='lance',
            new_name='sequencia',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='fornecedor',
            new_name='fornecedores',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='produto',
            new_name='produtos',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='ultimo_lance',
        ),
    ]
