# Generated by Django 4.0 on 2024-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0009_rename_produtos_projeto_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='projeto',
            name='fornecedor',
            field=models.ManyToManyField(to='appCotacao.Fornecedor'),
        ),
    ]
