# Generated by Django 4.0 on 2025-03-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0010_alter_cotacao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='total_lances',
            new_name='qtd_max_lances',
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Cotando'), (2, 'Aceitar ou Recusar'), (3, 'Finalizado com acordo'), (5, 'Finalizado sem acordo')], max_length=1, null=True),
        ),
    ]
