# Generated by Django 4.0 on 2024-07-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0010_remove_fornecedor_cnpj_projeto_fornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='nomeempresa',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='dono',
            new_name='responsavel',
        ),
    ]
