# Generated by Django 4.0 on 2024-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0011_rename_nome_fornecedor_nomeempresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('produto', 'fornecedor')},
        ),
        migrations.AddField(
            model_name='projeto',
            name='estrutura',
            field=models.ManyToManyField(to='appCotacao.Estrutura'),
        ),
        migrations.RemoveField(
            model_name='estrutura',
            name='projeto',
        ),
    ]
