# Generated by Django 4.0 on 2025-03-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0011_rename_total_lances_cotacao_qtd_max_lances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lance',
            old_name='dono',
            new_name='fornecedor',
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Cotando'), (2, 'Aceitar ou Recusar'), (3, 'Finalizado com sucesso'), (5, 'Finalizado sem sucesso')], null=True),
        ),
    ]
