# Generated by Django 4.0 on 2024-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0012_alter_estrutura_unique_together_projeto_estrutura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='estrutura',
            field=models.ManyToManyField(blank=True, to='appCotacao.Estrutura'),
        ),
    ]
