# Generated by Django 4.0 on 2025-03-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0012_rename_dono_lance_fornecedor_alter_cotacao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lance',
            old_name='fornecedor',
            new_name='dono',
        ),
    ]
