# Generated by Django 4.0 on 2024-07-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0013_alter_projeto_estrutura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='estrutura',
            field=models.ManyToManyField(null=True, to='appCotacao.Estrutura'),
        ),
    ]
