# Generated by Django 4.0 on 2025-03-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0013_rename_fornecedor_lance_dono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='lances',
            new_name='lances_old',
        ),
    ]
