# Generated by Django 4.0 on 2024-07-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0014_alter_projeto_estrutura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='estrutura',
            field=models.ManyToManyField(blank=True, to='appCotacao.Estrutura'),
        ),
    ]
