# Generated by Django 4.0 on 2025-03-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0014_rename_lances_cotacao_lances_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='historico_lances',
            field=models.JSONField(default=list, null=True),
        ),
    ]
