# Generated by Django 4.0 on 2024-07-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0015_alter_projeto_estrutura'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='estrutura',
        ),
        migrations.AddField(
            model_name='estrutura',
            name='projeto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appCotacao.projeto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='estrutura',
            unique_together={('produto', 'fornecedor', 'projeto')},
        ),
    ]
