# Generated by Django 4.0 on 2025-03-04 03:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCotacao', '0015_cotacao_historico_lances'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Fornecedor Não Trabalha com este produto'), (0, 'Custo/Fornecedor/Inicial'), (1, 'Custo/Carrefour'), (2, 'Custo/Fornecedor'), (3, 'Custo/Fornecedor/Aceitar|Recusar'), (4, 'Negociação de Custo cancelada'), (5, 'Aguardando Carrefour'), (6, 'Volume/Aguardando:Fornecedor'), (7, 'Volume/Aguardando:Carrefour'), (8, 'Volume/Fornecedor/Aceitar|Recusar'), (9, 'Cotação Cancelada'), (10, 'Cotação Finalizada')], default=0, null=True),
        ),
    ]
